apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:AfltmsDYFuVwVdOcrxI7mhaSNtPcwT5MWqDBY/7tQDK7F3+p5Sn5ImMcbwIIh+2ZOHSpJrLYOfhB6/xDtfMPsoGroCanNrCngefNFrq1260dhbcHw49akwJc7eKhQyZHf16BdyC0RFfhAV+xpBNCq9unYaMfLTN3PeqxMokaPB92fy+ZmM3hnZ4gtpmeVYs46Hjef9md2O5qhg7UQjdmlHAglUO5kE5thTnSBZH7BcayKzTHpd/GcbS1Jp6hBo+RI6PJXFRR6NoMY9FmKP21VPL9+NC6TvYvFq9hZ1MYMrFZz4Py0ed5wFmn9Xw=,iv:TvhtizLH0tCZGFvSBpb5su7U2FaTzxkU6nNhYc5WlTM=,tag:FH6RjRG60ohmyqkWqJUqcw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - recipient: age1esz4lnzpldg2tq223afk8lhf73adwpjxl0th6egf0xgukunjmazq36remj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUllxcjFPc1Ntc2N2Um9U
            a2lyT0w4ZGlXTDFIWlE0eVA0N2ZyMkhxM0JFCmJOWU5RdWJxYzFreCthTGFnQktN
            ZXZBallvTUZjNE96eDZJOHBWWEt0SFUKLS0tIGhpZmdBZ2gyQlRFUGVZdk5tYjBu
            dkh1Z1ZZNk9wNEUrdlpHakl0Nlo0b2sK0LSAEPDjSbSgWPFdwEDZUhGfNj0AsTWp
            FvZGgWHpVQMYsJdnILCyP3eogkpFZDjsiJpXPXbjE+GzubVmImmTQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-22T10:50:42Z"
    mac: ENC[AES256_GCM,data:zvi3sQz1gPMsZy9DCir1fo/Vuy1BJ52BwPBMkKkGt2Byc85fcJwIm6Jk9hlVYZ3RXuOn9WYZ+/DauleA4oIdoAxVB0fqQUQCnLe7lIMfdAMb+tKEOy8Nd2v7bxslV/F0GVh7o7awD7TYsg+huJkZkdv7Cpss/B+lpmmQI8Bq8ao=,iv:v4oUQIFdMdENtZhqpTtLHUkCWHP1nBNzUEjo0ahFRBQ=,tag:hN38/34Eazh4TRgRMTjwxA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2