apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:eRI0DoErgZByH/9SbYSO/rX/cx3NmNmBn0zc5IpYAQn4nRISG/c7iSB2wA1T6dS5MOR9OzCLB+LxAjl70WmIm48OZJcigO7d2mjcGlHcp+xewcArmoEau81YxFWJwFPE5pLK8uipF/jogY0zAVVwMSjrYgP6rf97SZ82COx3MZKshGil6PIpbiAVxLOiNA1rShkklakErN0N0CvNVcmQ+yXTo0XL/Pa4/i/nGmS77zaoLtprRgWwdnHO2H3SEkHR2680C9s7H6/B80icp3d1cubo6AKCiGpc/IxLBPVHOpWKWS3J/xf94IOq0sU=,iv:FRruzeRtE4XRput1MwX9d85Q8z9AX2oNfDUqC/Z5VPk=,tag:f45krnTX1HzmycZIQCguwQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - recipient: age14ez9p79ayp4wew9hu5rgtmutywyglqle5yzh83f5gw8ph9y6dfyq60wd35
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwOVlpa2pObGJDOW9uZ3Fo
            TWFUbkFzY1Q1Y2xuSVZLelh1eWI4R3BiTFZnCk9OeTBUemY0VTBHOUlpbnVDQjcz
            Zm53NVpRNG12Y1JLVUw5c0dHdTRqck0KLS0tIHVNUnNUbWdpNGdIU01XYjBZc3V4
            eXU1WFNaWXVMWkVyMS9MN2M3TWNtNGsKoAiV6C27sLvqi89ZuIs6+Qc66+wLajua
            ESWLJFnejMNMmACfn6C3sDqJdqYQQ5IOfGFbWlPmi3iHsOcP4mqW0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T09:54:16Z"
    mac: ENC[AES256_GCM,data:NZ+K7wpFtgVUIYR84GWHGhBiOS+xYwpqEhhuIChwDMv8/o1yGoDvDKsexgApYO1y4UjPanvR0auHSl/y20m0BSUkacTuFxR7Kxtgny8rQkU9idxFdyKAokkvIvvz5NjULCyj2MGqdz1ALMOZIFpEkX1WPE7TpZ1JNX2uX8zdr0k=,iv:l0NatI569j8Cb8bBLQyXFAGEV8ocrJqqPsrsw+yi8gM=,tag:dWAuIIaIMvZ2llSbwBOBDQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2