apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:wleaRyrylC4=,iv:ojh8d2HRh854Czowd5DAkzvU/2lpUuNMktCC2LmGMog=,tag:iHiPVR6L1zawvzmqlT29lw==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:EWfnbwpRDG8G7L36BNyIVU79u9wniJL4UPKQEg==,iv:1XCYvNhI/O5QuWuaCtXzxZ4Ky+dxsOHnb9xqKhOH6BI=,tag:jAb/lRQd+FFHM6Cey4CWRw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: linkding-container-env
sops:
    age:
        - recipient: age1nuryad77a7uf0u7cmeu4nlu68t5tax4wge3yfu56clg0h57msekqtcj6fv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcVBiN0Znc2RGaWNKQlV5
            YXZMZHB2eEVsWXI1UlJKNjhXSlo0elFIelZvCnNuUVdEaUZtcUtuZWt4QWk5bXFI
            RHk5Ui9Cc0twdExyaXZINzNOYkVuVTAKLS0tIDdydUFhT1FMdm9BTlo2Ri83eFRB
            Q2J5empJVDNjWm5VdWdadGdQc3l5VUUKtzhw6P5mny8vs6o+jR1Epc/6au5BfYP7
            Wglh5cp32az1XUNwqZykfDajedB8BoxSSY/VtdY0hQjrh6XKqn6elQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-23T10:42:07Z"
    mac: ENC[AES256_GCM,data:ssIPR8COaA3e+dqmzO6Ny3khCcIjPjWYSTd9WmctjZlihQTmi5sqOrhVCRQpPj5DAomJrVHVoopztE/CgM6L+gopOZlWU8lR9b0WapQJnnaPCxlm65toiKFGMQWtg7mIp8SZz5i8YVB+IgFJoMRaPsshS8FJmasdGE9VME2xC00=,iv:gtYD52I8WmE/DQErIu8RJFtL0OYFCIyPbsVpKNa9gQA=,tag:OiqXLb5K8Ictp5E+If6OCA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2