creation_rules:
  # note: Process all yaml files
  - path_regex: \.yaml$
    # note: Encrypted regex for data and stringData fields
    encrypted_regex: ^(data|stringData)$
    # note: Public key for encryption / decryption
    age: age1esz4lnzpldg2tq223afk8lhf73adwpjxl0th6egf0xgukunjmazq36remj