apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding
resources:
  - ../../base/linkding
  # info: Not exposing Services in staging. Region for testing purposes only.
  #- cloudflared.yaml