apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding
resources:
  - ../../base/linkding
  - cloudflared.yaml # note: Uncomment if you want to deploy cloudflared tunnel
  - tunnel-credentials.yaml