apiVersion: v1
data:
    password: ENC[AES256_GCM,data:MfzkKRNtp4Le/mFp,iv:sT0qn8rMuDvTU67eipjiPXGXpSkcAeXoMXg1nSIH9Rg=,tag:ORPFzETeZVFUo8CnGmFi7w==,type:str]
    user: ENC[AES256_GCM,data:TdzAzxYW1nTLGixK,iv:MixM+gZQAolyu/C26wdFEdmHeKxekMREbyohvcUZF9w=,tag:v0RX746x14YkomLHTgBW2Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: test-secret
sops:
    age:
        - recipient: age1nuryad77a7uf0u7cmeu4nlu68t5tax4wge3yfu56clg0h57msekqtcj6fv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBYnJSNWtjelVVSmgza1B3
            eU5ldUZrbWxnVVI1TGQvelR0Y3kwc2pBelI4CkVVT0pzRnRRYk8yTUd1SXRLTXdT
            VFM0YzFPdzNYZ3o5UElJb3hCVEgrWjgKLS0tIHcybW9DOGhjSkhTM00rY1FKQys0
            RnBjRVlQcVNUTnAvcXBucTJXTHZzR2cKzIXAFEE5BWxDuiEEoV6roNgFhtIZfws9
            J9Tz9o8B3lSFnqrkmreS2ptKQ/c9xWPlFPUNyCuQW/Ok6jwwaWlLlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-09T12:43:32Z"
    mac: ENC[AES256_GCM,data:Yg5RubaKsimznKR5yK6iNBgqWCtE5X8+FWJ5WZy6bzwmb50YbK+KU8SxOGDn1akeeK8omzExuvzpBBAWM2XAFLfP+EY7/y4zVVMmoUFPXBrPSvyjxs1vExgrUJb+YH0boXhqIoDXGVyTnfzNx4nKa3BFgn4bN7hwJXyX9E6MurY=,iv:ESbBbpU817vdQABrUSw1+ncGQ8dPv9HPCDrCitLqvhE=,tag:DXhajnaJHIijvQS/JlkgQA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2