creation_rules:
  # note: Process all yaml files
  - path_regex: \.yaml$
    # note: Encrypted regex for data and stringData fields
    encrypted_regex: ^(data|stringData)$
    # note: Public key for encryption / decryption
    age: age1nuryad77a7uf0u7cmeu4nlu68t5tax4wge3yfu56clg0h57msekqtcj6fv 