apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack # note: this is the name of the HelmRepository chart in that repository
      #version: "66.2.2" # note: can be pinned to a specific version
      version: "75.*" # note: can be pinned to a major version, e.g., "66.*". Version will be checked at interval (above).

      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack # note: this is the name of the HelmRepository resource maintained by repository.yaml
        namespace: monitoring
      interval: 12h
  install:

    # !! Create will create the CRDs (Custom Resource Definitions). CRD's created by this chart are not removed by default and should be manually cleaned up if the chart is uninstalled. More info: https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#uninstall-helm-chart

    crds: Create 

  upgrade:

    # !! The upgrade strategy is set to CreateReplace, which will replace existing resources with new ones during upgrades. This is useful for CRDs and other resources that may not be compatible with in-place updates. 

    crds: CreateReplace

  driftDetection:
    mode: enabled # note: helm release is the only source of truth for this chart. No manual changes should be made to the resources created by this chart.
    ignore:
      # Ignore "validated" annotation which is not inserted during install
      - paths: ["/metadata/annotations/prometheus-operator-validated"]
        target:
          kind: PrometheusRule
  values:
    grafana:
      adminPassword: ENCRYPT_ME!
