apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
# info: Security Context
      securityContext:
        fsGroup: 33 # note: update volume permissions forwww-data group ID
        runAsUser: 33 # note: runas www-data user ID
        runAsGroup: 33 # note: runas www-data group ID
# info: Containers
      containers:
        - name: linkding
          image: sissbruecker/linkding:1.31.0

          ports:
            - containerPort: 9090

          securityContext:
            allowPrivilegeEscalation: false # note: disable privilege escalation

      #envFrom: # note: use envFrom to load environment variables - create user in this case
        #- configMapRef:
        #    name: linkding-configmap
        #- secretRef:
        #    name: linkding-container-env # note: 

          volumeMounts: # note: mount the persistent volume
            - name: linkding-data
              mountPath: /etc/linkding/data
      volumes:
        - name: linkding-data
          persistentVolumeClaim:
            claimName: linkding-data-pvc # note: use the PVC created in storage.yaml