apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path # note: use the storage class available in your cluster (k get storageclasses)
  resources:
    requests:
      storage: 1Gi